--SEM1 
SELECT* FROM EMPLOYEES ORDER BY 1; --FIRST COLUMN
SELECT* FROM EMPLOYEES ORDER BY 2;

--PL/SQL




--CONSTRUCT A PLSQL BLOCK DISPLAYING THE FIRST NAME AND LAST NAME OF EMPLOYEE 100
--DESC EMPLOYEES;
--SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID=100;

SET SERVEROUTPUT ON

DECLARE 
V_FIRST_NAME  VARCHAR2(3);
V_LAST_NAME VARCHAR2(30);

BEGIN 
    SELECT FIRST_NAME, LAST_NAME INTO V_FIRST_NAME, V_LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID=201;
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME||' '||V_LAST_NAME);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('THE EMPLOLYEES DOESN''T EXIST');
        WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('THE SELECT RETRURNS MORE THAN 1 EMPLOYEE');
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ANOTHER EXCEPTION-'||SQLERRM);
END;
/

-- DECLARE THE EMPLOYEES WHO HACE AT LEAST ONE ORDER
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID  IN (SELECT SALES_REP_ID FROM ORDERS);

--DECLARE THE EMPLOYEES WHO HAVE NO ORDERS
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID  NOT IN (SELECT SALES_REP_ID FROM ORDERS
WHERE SALES_REP_ID IS NOT NULL);


DECLARE
V_GRADE NUMBER(2) DEFAULT 7; --DEFAULT CAN BE USED TO INITIALIZE A VAR IN THE DECLARE PART OF THE BLOCK
--NESTED IF
BEGIN
V_GRADE :=3; --IS THE ASSIGNMENT OPERATOR
    CASE
    WHEN V_GRADE<1 OR V_GRADE>10 THEN
    DBMS_OUTPUT.PUT_LINE('WRONG GARDE ');
     WHEN V_GRADE =10 THEN
    DBMS_OUTPUT.PUT_LINE('PRIZE');
    WHEN V_GRADE >=5 THEN
    DBMS_OUTPUT.PUT_LINE('PASSED');
    DBMS_OUTPUT.PUT_LINE('CONGRATS');
    WHEN V_GRADE IS NULL THEN
     DBMS_OUTPUT.PUT_LINE('NO GRADE ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FAILED');
        DBMS_OUTPUT.PUT_LINE('STUDY HARDER');
    END CASE;
      DBMS_OUTPUT.PUT_LINE('1');

END;
/



