--THE LOOP
SET SERVEROUTPUT ON
DECLARE 
    V_STRING VARCHAR2(100):= 'AAAA578AAAAAAL';
    V_VOWELS VARCHAR2(100); --UEIOUE
    V_CONSONANTS VARCHAR2(100); --JDKWHSK
    V_CHAR VARCHAR2(100);
    V_OTHERS VARCHAR2(100);
    V_CHAROTHERS VARCHAR2(100);
    I PLS_INTEGER:=1;
BEGIN
    FOR  I IN REVERSE 1..100 LOOP
    DBMS_OUTPUT.PUT_LINE(I);
    END LOOP;
    
     WHILE (I<LENGHT(V_STRING)) LOOP
       IF SUBSTR(UPPER((V_STRING),I,1) NOT BETWEEN 'A' AND 'I' THEN
        V_OTHERS:=V_OTHERS||SUBSTR(UPPER(V_STRING,I,1);
       ELSIF SUBSTR(UPPER(V_STRING),I,1) IN ('A','E','I','O','U') THEN
        V_VOWELS:=V_VOWELS \\SUBSTR(UPPER(V_STRING),I,1);
       ELSE
        V_CONSONANTS:=V_CONSONANTS ||SUBSTR(UPPER(V_STRING),I,1);
        ENDIF;
        EXIT WHEN (I=LENGTH(V_STRING));
        I:=I+1;
       
        
        
        
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Vowels: ' || V_VOWELS);
    DBMS_OUTPUT.PUT_LINE('Consonants: ' || V_CONSONANTS);
    DBMS_OUTPUT.PUT_LINE('Others: ' ||V_OTHERS);
    DBMS_OUTPUT.PUT_LINE('I='||I);

    
END;
/

SELECT* FROM EMPLOYEES ORDER BY 1;
--USING A PLSQL BLOCK DISAPLY THE EMPLOYEES FROM DEPARTEMNT 30 AND 50
DESC EMPLOYEES;

SSELECT* FROM COUNTRIES;
DECLARE 
    --V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    --V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE;
    --V_MAX PLS_INTEGER;
    --V_MIN PLS_INTEGER;
    V_NAME VARCHAR2(100);
    TYPET_VAL IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
    V T_VAL;

BEGIN

    SELECT FIRST_NAME||' '||LAST_NAME AS DO BULK COLLECT INTO V FROM EMPLOYEES ORDER BY EMPLOYEE_ID;
    FOR I IN V.FIRST..V.LAST LOOP
        DBMS_OUTPUT.PUT_LINE;
        
  
   END LOOP;     
    
END;
/